name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Run Tests
      id: run-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Run Tests
        setup-command: ''
        command: cargo test
        timeout: 1
        max-score: 1
    - name: Format & Clippy
      id: format-clippy
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Format & Clippy
        setup-command: ''
        command: cargo fmt --check &&  cargo clippy --all-targets --all-features --
          -D warnings
        timeout: 1
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUN-TESTS_RESULTS: "${{steps.run-tests.outputs.result}}"
        FORMAT-CLIPPY_RESULTS: "${{steps.format-clippy.outputs.result}}"
      with:
        runners: run-tests,format-clippy
